services:
  dev:
    platform: linux/arm64
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        BUILDPLATFORM: linux/arm64
        TARGETPLATFORM: linux/arm64
    container_name: gateway-dev
    depends_on:
      - localstack
    volumes:
      - ..:/work:cached
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /work
    tty: true
    networks:
      - local-gateway

networks:
  local-gateway:
    external: false
